name: CD/CI
run-name: Build Job ${{ github.event.head_commit.message }} by @${{ github.actor }}
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Install dependeces
        run: mvn install -f ./mlalgo/pom.xml
      - name: Compile project
        run: mvn compile -f ./mlalgo/pom.xml

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run unit-test
        run: mvn test -f ./mlalgo/pom.xml